### PR TITLE
Fix multi chunk

### PR DESCRIPTION
**Pull request by dourgulf**
There is bug, when sever send multiple chunk, it will insert a byte of 0xC? (0xC3 especially). It will corrupt the handleMessage. 
and have something log like this:
received unknown packet type: 0x15
Maybe it is the bug of issue #47  #151  

I try to fix this problem by reassemble the buffer, remove the chunk indicator(0xC?).

(I think there will be other bug if server can't send a complete package every time.)

### CODE REVIEW

**Comment by dourgulf** [comment]
There is bug, when sever send multiple chunk, it will insert a byte of 0xC? (0xC3 especially). It will corrupt the handleMessage.
and have something log like this:
received unknown packet type: 0x15
Maybe it is the bug of issue #47 #151

I try to fix this problem by reassemble the buffer, remove the chunk indicator(0xC?).

(I think there will be other bug if server can't send a complete package every time.)

**Comment by dourgulf** [comment]
Sorry, I am newer, make a duplicate pull request

**Comment by jgh-** [comment]
It's OK, thanks for your contribution. I'll close the other one.  I just want to give this one a quick test this morning before merging.

**Comment by dourgulf** [comment]
I do a simple test by modifing the nginx-rtmp-module project , make it send response message with multiple chunk:
1. Change the configure file make default chunk size to 128 byte
2. Modify the source file, add more chars in connect response text (ngx_rtmp_cmd_connect function).

**Comment by dourgulf** [comment]
Find a BUG for this pull request:When TCP package size large then a message size, it will destroy the next message.

**Comment by satyamub** [comment]
@dourgulf Did you find any issue, As I made the outchunksize to 128 in Adobe Media Server, I am getting this 
received unknown packet type: 0x15

Can you help me on this???

**Comment by dourgulf** [comment]
@satyamub update the last code, this issue shoult be fixed

**Pull request closed without merging**
