### PR TITLE
Add dynamic changing filters

### PR DESCRIPTION
**Pull request by havocked**
- Add a button near the connect button to show the changing between the existing filters. (In the sample project)
- Add Enum for filters
- Add property filter in VCSimplesession
- Add setter for the property filter

### CODE REVIEW

**Comment by jgh-** [comment]
looks good.

**Comment by havocked** [comment]
I changed storyboard and podfile for the purpose of testing in the sample project, I might have commit modification in related files that you might not want ?

**Comment by havocked** [comment]
Hi,

Thanks for the merge !

Just wanted to know when it could be available in the official cocoapod ? While it be with the next release 0.3.2 ?

Thanks again for your great work !

**Comment by jgh-** [comment]
ill put the pod together today!

**Comment by KCastiglione** [comment]
Is there a reason Fisheye is not included in the enum for filters?

**Comment by JALsnipe** [comment]
No idea, but you can just add the `com.videocore.filters.fisheye` identifier and roll it out yourself.

**Comment by havocked** [comment]
Hi,  during my testing I didn't add it because I had a bug only with this one. I'll try another test later this week and add a pull request.

**Comment by JALsnipe** [comment]
What was the bug?  I wrote the filter, so maybe there's something I can change or tweak.

**Comment by KCastiglione** [comment]
@JALsnipe  Yes good idea, I can add 'com.videocore.filters.fisheye' identifier, but it will be easy to maintain if it is in the main repository and part of Pods, and Fisheye is a great filter! Thanks for the Fisheye filter

**Pull request merged**
