### PR TITLE
Custom Video Filters

### PR DESCRIPTION
**Pull request by JALsnipe**
I'm very new to OpenGL ES but wanted to try my hand at some filters.  I'm using your `BasicVideoFilterBGRA` class as the base, and just added the shader to `vertexKernel()`.

This first commit adds a greyscale filter:
img_0352

Let me know how your want to proceed with the filters.  Should the shaders be abstracted into their own `.fsh` files and loaded into a main filter class?

### CODE REVIEW

**Comment by jgh-** [comment]
I think this looks pretty good, but I'm not sure if I like the "Custom" folder - I was sort of thinking there could be a basic suite with filters such as GrayScale and perhaps things like Sepia and other common image filters.  If "Basic" is not an agreeable location for them we can sort of brainstorm that.  I think perhaps the default filters can go into either the "Basic" folder or we can rename "Basic" to "Default"?

In any case, if you do either of those things I'll merge this because it looks good otherwise.

On your other question, I think that it would be better to make them compiled filters because it's conceivable in that in the future people will want to make more complex shaders that have more than the few default uniforms and attributes provided (i.e. filters that change over time, filters that actually change the geometry of the image, etc).

**Comment by JALsnipe** [comment]
I like the idea of a "Basic" folder.  Will update as I have time this weekend and will possibly add some more filters.  Thanks for the feedback!

**Comment by JALsnipe** [comment]
@jgh- please review at your convenience.

**Comment by jgh-** [comment]
Looks good, thanks!

**Pull request merged**
