### PR TITLE
Adding the ability to set Mirroring on for front camera

### PR DESCRIPTION
**Pull request by lelikg**
a nicer experience when streaming from front camera

### CODE REVIEW

**Comment by lelikg** [comment]
found a few issues, will update and repost

**Comment by jgh-** [comment]
This will also mirror the output

**Comment by lelikg** [comment]
I’m working on an updated version, will create a new pr

**Comment by jgh-** [comment]
The easiest way to do this is by applying an affine transform to the preview view

**Comment by lelikg** [comment]
Thanks for the tip, I did that! great library by the way.
I have an issue that is unrelated to mirroring. The second I stop the RTMP session, whatever I had in my stream buffer does not get transmitted to the RTMP server.
I mean - when I am streaming, the last 5 seconds of the stream get cut off. How do I keep that from hapenning?
I thought of setting a timer on my “stop” button and just waiting 5 or 10 seconds, but there must be a better way of flushing the buffer in the background or something?
What do you think?

**Pull request closed without merging**
